development:
  clients:
    default:
      database: task_manager
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: task_manager_test
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: task_manager
      hosts:
        - 10.0.7.30:27017
  options:
    raise_not_found_error: false

staging:
  clients:
    default:
      database: task_manager
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
